# ########################################################### #
# Guide Plugin Developer: PopoGonry ( rhtjdsh35@gmail.com )
# ########################################################### #

# Guide Plugin Config File #

# Menu GUI Item

GUI-Name: "Menu"


# {미션넘버} / {미션제목}
Item-Name: "&f[&6{미션넘버}&f] &7{미션제목}"

# {미션넘버} / {미션제목} / {미션클리어설명}
Item-Lore:
    - "&a클리어 방법"
    - "{미션클리어설명}"

