name: GuidePlugin
version: '1.0-SNAPSHOT'
main: com.popogonry.guidePlugin.GuidePlugin
api-version: '1.21'
softdepend: ["PlaceholderAPI"]
depend: ["AdvancedEnchantments", "InfinityTowerPlugin", "AdvancedEnchantments", "Lands", "ClueScrolls", "BetterRTP", "CustomCrops", "Evolution"]

commands:
  tuguide:
  ng: